version: '3'

services:
  traefik:
    image: traefik:1.7.2-alpine
    ports:
      - "80:80"
    volumes:
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.frontend.rule=Host:monitor.localtest.me"
      - "traefik.port=8080"
      - "traefik.enable=true"

  auth:
    image: node
    volumes:
      - .:/src
    working_dir: /src
    command: npm start
    labels:
      - "traefik.frontend.rule=Host:auth.localtest.me"
      - "traefik.port=3000"

  closed:
    image: emilevauge/whoami:latest
    labels:
      - "traefik.frontend.rule=Host:closed.localtest.me"
      - "traefik.frontend.auth.forward.address=http://auth:3000/auth"
      - "traefik.frontend.auth.forward.authResponseHeaders=cookie"

  open:
    image: emilevauge/whoami:latest
    labels:
      - "traefik.frontend.rule=Host:open.localtest.me"


 # docker run -w /src -v c:/Users/mark/dev/auth:/src --name auth --network auth_default node npm start
