global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'docker'
    static_configs:
      - targets: ['172.18.0.1:9323']
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
  - job_name: 'grafana'  
    static_configs:
      - targets: ['grafana:3000']

