## traefik.yml
log:
  level: INFO

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: dynamic.yml
    watch: true

# API and dashboard configuration
api:
  insecure: false

metrics:
  prometheus: {}

certificatesResolvers:
  sample:
    acme:
      email: mark@oosterveld.org
      storage: acme.json
      httpChallenge:
        entryPoint: http

