loglevel = "DEBUG"

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
  [entryPoints.http]
    address = ":80"

[api]
  entrypoint="dashboard"

[docker]
  domain = "localhost"
  watch = true
